version: '3.4'

services:
  quantumania:
    image: quantumania
    build:
      context: .
      dockerfile: ./quantumania/Dockerfile.quantumania
    depends_on:
      - db
    networks:
      - internal
      
  nginx:
    image: openquantumsafe/nginx
    ports:
      - 443:4433
    volumes:
      - ./nginx/nginx.conf:/opt/nginx/nginx-conf/nginx.conf
      - ../frontend/src/dist:/opt/nginx/html
    depends_on:
      - quantumania
    networks:
      - default
      - internal



  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=quantumania
      - MYSQL_USER=quantumania
      - MYSQL_PASSWORD=quantumania
      - MYSQL_DATABASE=quantumania
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

networks:
  default:
  internal:
    internal: true