version: '3.4'

services:
  quantumania:
    image: silvercryptor/quantumania
    depends_on:
      - db
    networks:
      - internal
      
  nginx:
    image: silvercryptor/quantumania-nginx
    ports:
      - 443:4433
    depends_on:
      - quantumania
    networks:
      - default
      - internal


  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=quantumania
      - MYSQL_USER=quantumania
      - MYSQL_PASSWORD=quantumania
      - MYSQL_DATABASE=quantumania
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - internal
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

networks:
  default:
  internal:
    internal: true