FROM openquantumsafe/nginx


COPY ./nginx.conf /opt/nginx/nginx-conf/nginx.conf

# get front-end artifact from github actions
COPY frontend.tar.gz /tmp/frontend.tar.gz
RUN tar -xzvf /tmp/frontend.tar.gz --strip-components=1 -C /opt/nginx/html

