version: '3.4'

services:
  nginx_libqos:
    image: openquantumsafe/nginx
    container_name: nginx-libqos
    ports:
      - 443:4433
    volumes:
      - ./nginx.conf:/opt/nginx/nginx-conf/nginx.conf
      - ../../frontend/src/dist:/opt/nginx/html